---

- name: Configure hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'

- name: Configure timezone
  community.general.timezone:
    name: America/New_York

- name: Create user
  ansible.builtin.user:
    name: '{{ username }}'
    shell: /bin/bash
    append: true
    groups: sudo

- name: Create sudo config for user
  ansible.builtin.template:
    src: sudo_user.j2
    dest: /etc/sudoers.d/vitaliy
    owner: root
    group: root
    mode: 0400

- name: Install dependencies
  ansible.builtin.apt:
    name: '{{ item }}'
    autoremove: true
    clean: true
    state: present
  with_items:
    - bind9-dnsutils
    - curl
    - ethtool
    - hdparm
    - htop
    - iftop
    - iotop
    - jq
    - lftp
    - lm-sensors
    - lshw
    - mtr
    - neovim
    - net-tools
    - netcat-traditional
    - nmap
    - openssh-client
    - openssh-server
    - pv
    - tcpdump
    - tmux
    - tree
    - unzip
    - wget
    - whois
