---

- name: Restart Prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Restart Alertmanager
  ansible.builtin.service:
    name: prometheus-alertmanager
    state: restarted
