---

- name: Install desktop related packages
  ansible.builtin.apt:
    name: '{{ item }}'
    autoremove: true
    clean: true
    state: present
  with_items:
    - abcde
    - ansible
    - arandr
    - asdftool
    - feh
    - firefox-esr
    - fonts-font-awesome
    - fonts-liberation
    - fonts-noto-core
    - fonts-noto-mono
    - fonts-open-sans
    - fonts-terminus-otb
    - git
    - keepassx
    - kitty
    - musikcube
    - pulsemixer
    - sway
    - syncthing
    - telegram-desktop
    - tig
    - vlc
    - weechat

- name: Populate NeoVIM config
  ansible.builtin.template:
    dest: /home/{{ username }}/.config/nvim/init.vim
    group: '{{ username }}'
    mode: "0640"
    owner: '{{ username }}'
    src: nvim_init.j2

- name: Populate Sway config
  ansible.builtin.template:
    dest: /home/{{ username }}/.config/sway/config
    group: '{{ username }}'
    mode: "0640"
    owner: '{{ username }}'
    src: sway.config.j2

- name: Create config.d for sway
  ansible.builtin.file:
    group: '{{ username }}'
    mode: "0640"
    owner: '{{ username }}'
    path: /home/{{ username }}/.config/sway/config.d
    state: directory

- name: Populate Sway startup config
  ansible.builtin.template:
    dest: /home/{{ username }}/.config/sway/config.d/startup.conf
    group: '{{ username }}'
    mode: "0640"
    owner: '{{ username }}'
    src: sway_startup.conf.j2

- name: Populate Sway theme config
  ansible.builtin.template:
    dest: /home/{{ username }}/.config/sway/config.d/theme.conf
    group: '{{ username }}'
    mode: "0649"
    owner: '{{ username }}'
    src: sway_theme.conf.j2

- name: Populate Kitty config
  ansible.builtin.template:
    dest: /home/{{ username }}/.config/kitty/kitty.conf
    group: '{{ username }}'
    mode: "0640"
    owner: '{{ username }}'
    src: kitty.conf.j2
