---

- name: Install libvirt
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - qemu-system
    - libvirt-daemon-system

- name: Start libvirtd
  ansible.builtin.service:
    name: libvirtd
    enabled: yes
    state: started
