---

- name: Install libvirt
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  with_items:
    - libvirt-daemon-system
    - qemu-system

- name: Start libvirtd
  ansible.builtin.service:
    enabled: true
    name: libvirtd
    state: started

- name: Add user to libvirt group
  ansible.builtin.user:
    append: true
    groups: libvirt
    name: "{{ username }}"

- name: Create /srv/libvirt
  ansible.builtin.file:
    group: libvirt
    mode: "0775"
    owner: libvirt-qemu
    path: /srv/libvirt
    state: directory
