---

- name: Install Prometheus
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  with_items:
    - prometheus
    - prometheus-alertmanager

- name: Populate Prometheus config
  ansible.builtin.template:
    dest: /etc/prometheus/prometheus.yml
    group: root
    mode: "0644"
    owner: root
    src: prometheus.yml.j2
  notify:
    - Restart Prometheus

- name: Populate Alertmanager config
  ansible.builtin.template:
    dest: /etc/prometheus/alertmanager.yml
    group: root
    mode: "0644"
    owner: root
    src: alertmanager.yml.j2
  notify:
    - Restart Alertmanager

- name: Start and enable Prometheus service
  ansible.builtin.service:
    enabled: true
    name: prometheus
    state: started

- name: Start and enable Alertmanager service
  ansible.builtin.service:
    enabled: true
    name: prometheus-alertmanager
    state: started
