---

- name: Stop Docker service
  ansible.builtin.service:
    name: docker
    state: stopped

- name: Remove Docker
  ansible.builtin.apt:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker-compose
    - docker.io

- name: Install Podman
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  with_items:
    - podman
    - podman-compose

- name: Set sysctl net.ipv4.ip_unprivileged_port_start=53
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: 53
    state: present
    sysctl_file: /etc/sysctl.d/podman.conf

